version: 2

sources:
  - name: mailchimp_raw
    database: mailchimp_data
    schema: raw
    tables:
      - name: mailchimp_bronze_campaigns
        description: ""
        columns:
          - name: json_data
            description: ""
          - name: extract_date
            description: ""
          - name: file_name
            description: ""
      - name: mailchimp_bronze_email_activity
        description: ""
        columns:
          - name: json_data
            description: ""
          - name: extract_date
            description: ""
          - name: file_name
            description: ""
      # - name: mailchimp_bronze_lists
      #   description: ""
      #   columns:
      #     - name: json_data
      #       description: ""
      #     - name: extract_date
      #       description: ""
      #     - name: file_name
      #       description: ""
      # - name: mailchimp_bronze_reports
      #   description: ""
      #   columns:
      #     - name: json_data
      #       description: ""
      #     - name: extract_date
      #       description: ""
      #     - name: file_name
      #       description: ""